= plantuml-generator project

image:https://sonarcloud.io/api/project_badges/measure?project=devlauer_plantuml-generator&metric=ncloc["Lines of Code", link="https://sonarcloud.io/summary/new_code?id=devlauer_plantuml-generator"]

image:https://sonarcloud.io/api/project_badges/measure?project=devlauer_plantuml-generator&metric=security_rating["Security Rating", link="https://sonarcloud.io/summary/new_code?id=devlauer_plantuml-generator"]

image:https://sonarcloud.io/api/project_badges/measure?project=devlauer_plantuml-generator&metric=vulnerabilities["Vulnerabilities", link="https://sonarcloud.io/summary/new_code?id=devlauer_plantuml-generator"]

image:https://sonarcloud.io/api/project_badges/measure?project=devlauer_plantuml-generator&metric=sqale_rating["Maintainability Rating", link="https://sonarcloud.io/summary/new_code?id=devlauer_plantuml-generator"]


== Description 

plantuml-generator is a project which consists of a utility module which can be 
used to generate link:http://plantuml.com/[PlantUML] class diagrams from existing 
java classes and its maven plugin frontend.

With the help of this project you can generate class diagrams for your project
documentation on the fly during each maven build or via the utility module.

== Documentation

The documentation for this project can be found at 
link:https://devlauer.github.io/plantuml-generator/plantuml-generator/latest/index.html[].

If you are only interested in the maven plugins you can directly go to
link:https://devlauer.github.io/plantuml-generator/plantuml-generator-maven-plugin/latest/index.html[]

If you want to use the utility classes on their own you can directly go to
link:https://devlauer.github.io/plantuml-generator/plantuml-generator-util/latest/index.html[]

== Licensing

This software is licensed under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache Licence, Version 2.0]. 
Note that plantuml-generator has several dependencies which are not licensed under the 
Apache License. 
Note that using plant-uml-generator comes without any (legal) warranties.

== Versioning

This project uses sematic versioning. 
For more information refer to http://semver.org/[semver].

== Changelog

This plugin has a dedicated 
link:https://github.com/devlauer/plantuml-generator/blob/master/Changelog.adoc[Changelog].

== Reporting bugs and feature requests

Use GitHub issues to create your issues.

== Source

Latest and greatest source of plantuml-generator can be found on 
https://github.com/devlauer/plantuml-generator[GitHub]. Fork it!
