= maxVisibilityFields
include::./_attributes.adoc[]

include::partial$class-diagram/max-visibility-fields.adoc[leveloffset=+1]

== Example

=== Maximum visibility public

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilityfieldspublic]
----
[sidebar]
--
<1> set maximum visibility for fields to *public* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_fields_public_diagram,png]
----
include::example$testresources/class/0013_max_visibility_fields_public.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0013_max_visibility_fields_public.txt[]
----

=== Maximum visibility protected

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilityfieldsprotected]
----
[sidebar]
--
<1> set maximum visibility for fields to *protected* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_fields_protected_diagram,png]
----
include::example$testresources/class/0013_max_visibility_fields_protected.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0013_max_visibility_fields_protected.txt[]
----

=== Maximum visibility package private

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilityfieldspackageprivate]
----
[sidebar]
--
<1> set maximum visibility for fields to *package private* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_fields_package_private_diagram,png]
----
include::example$testresources/class/0013_max_visibility_fields_package_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0013_max_visibility_fields_package_private.txt[]
----

=== Maximum visibility private

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilityfieldsprivate]
----
[sidebar]
--
<1> set maximum visibility for fields to *private* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_fields_private_diagram,png]
----
include::example$testresources/class/0013_max_visibility_fields_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0013_max_visibility_fields_private.txt[]
----

