= maxVisibilityMethods
include::./_attributes.adoc[]

include::partial$class-diagram/max-visibility-methods.adoc[leveloffset=+1]

== Example

=== Maximum visibility public

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilitymethodspublic]
----
[sidebar]
--
<1> set maximum visibility for methods to *public* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_methods_public_diagram,png]
----
include::example$testresources/class/0014_max_visibility_methods_public.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0014_max_visibility_methods_public.txt[]
----

=== Maximum visibility protected

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilitymethodsprotected]
----
[sidebar]
--
<1> set maximum visibility for methods to *protected* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_methods_protected_diagram,png]
----
include::example$testresources/class/0014_max_visibility_methods_protected.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0014_max_visibility_methods_protected.txt[]
----

=== Maximum visibility package private

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilitymethodspackageprivate]
----
[sidebar]
--
<1> set maximum visibility for methods to *package private* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_methods_package_private_diagram,png]
----
include::example$testresources/class/0014_max_visibility_methods_package_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0014_max_visibility_methods_package_private.txt[]
----

=== Maximum visibility private

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/classdiagram/{generatorclass}Test.java[tags=maxvisibilitymethodsprivate]
----
[sidebar]
--
<1> set maximum visibility for methods to *private* in the configuration
--

which is rendered this way:

[plantuml,0013_max_visibility_methods_private_diagram,png]
----
include::example$testresources/class/0014_max_visibility_methods_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0014_max_visibility_methods_private.txt[]
----

