= removeFields
include::./_attributes.adoc[]

== Description

With this configuration toggle you can remove all fields 
from the generated diagram text.

If you want to remove specific fields from the diagram, 
you have to use the
xref:./field-blacklist-regexp.adoc[field blacklist regular expression]
configuration option.

If you want to hide all fields on the rendered diagram but do not want to 
remove them from the diagram text, you have to use the
xref:./hide-fields.adoc[hide fields]
configuration option.

== Default value

The default value of this configuration option is false (nothing is removed).

== Example

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/{generatorclass}Test.java[tags=removefields]
----
[sidebar]
--
<1> toggle "remove fields" configuration
--

which is rendered this way:

[plantuml,0016_remove_fields_diagram,png]
----
include::example$testresources/class/0016_remove_fields.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0016_remove_fields.txt[]
----
