= whitelistRegexp
include::./_attributes.adoc[]

== Description

This configuration parameter defines a regular expression for all classes
which should be part of the generated diagram text.
It can not be combined with a 
xref:./blacklist-regexp.adoc[blacklist regular expression] 
or a 
xref:./scanpackages.adoc[list of packages to scan for].
Therefore it can only be added to the constructor of the {builderclass}
class as a single parameter. 

== Default value

If not specified the default value is null (ignored).

== Example

Here is an example from the JUnit tests using this configuration parameter:

[source,java,indent=0]
----
include::example$testsrc/de/elnarion/util/plantuml/generator/{generatorclass}Test.java[tags=whitelistregexp]
----
[sidebar]
--
<1> the blacklist regular expression is always added as string in combination
with the list of packages to scan to the {builderclass}
--

which is rendered this way:

[plantuml,0012_jar_whitelist_diagram,png]
----
include::example$testresources/class/0012_jar_whitelist.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::example$testresources/class/0012_jar_whitelist.txt[]
----

