= Class diagram generator mojo

If you want to use the plantuml-generator-maven-plugin for class diagram generation,
you need to configure this plugin as any normal maven plugin as part of your build and 
add this plugin specific configuration:

* required configuration parameters:
** *xref:class-diagram/config/output-filename.adoc[outputFilename]* - 
  the file name of the diagram generated by this plugin; required

* mutually exclusive configuration parameters
** *xref:class-diagram/config/scanpackages.adoc[scanPackages]* -
  a string list of all packages which should be used to generate the class diagram; 
  required in conjunction with the blacklist regular expression and optional with the
  whitelist regular expression
** *xref:class-diagram/config/whitelist-regexp.adoc[whitelistRegexp]* - a regular expression to filter all classes in the classpath which 
should be part of the diagram (processing can be speed up with the scanPackages 
configuration); optional +
if a whitelist regular expression is configured the blacklist regular expression is ignored!
** *xref:class-diagram/config/blacklist-regexp.adoc[blacklistRegexp]* - a regular expression to remove classes from the list of classes in the 
diagram - works only if the configuration parameter scanPackages is not empty and no 
whitelist regular expression is defined; optional


* optional configuration options:
** *xref:class-diagram/config/additional-plantuml-configs.adoc[additional-planuml-configs]*+
  this parameter allows to add special plantuml configuration options to the 
  beginning of the plantuml diagram like 'left to right direction'.
** *xref:class-diagram/config/add-jpa-annotations.adoc[addJPAAnnotations]* - a boolean to express if JPA-annotations should be shown in
the diagram; optional - Default ``false`` +
Currently implemented JPA Annotations are 
+
--
*** javax.persistence.Column, 
*** javax.persistence.Id, 
*** javax.persistence.Transient, 
*** javax.persistence.OneToOne, 
*** javax.persistence.OneToMany, 
*** javax.persistence.ManyToMany, 
*** javax.persistence.ManyToOne,
*** javax.persistence.Entity, 
*** javax.persistence.Table, 
*** javax.persistence.MappedSuperclass, 
*** javax.persistence.Index and
*** javax.persistence.UniqueConstraint 
--
+
Index, UniqueConstraint, Tablename and Tableschema are show as tagged values in a separate compartment
** *xref:class-diagram/config/asciidoc-diagram-name.adoc[asciidocDiagramName]* - the name of the diagram in the asciidoc diagram block - 
default is outputFilename + "." + asciidocDiagramImageType;optional
(only used when enableAsciidocWrapper is true);
** *xref:class-diagram/config/asciidoc-diagram-image-format.adoc[asciidocDiagramImageFormat]* - the image format (png/svg/latex etc.) - default is ``png``; optional
(only used when enableAsciidocWrapper is true);
** *xref:class-diagram/config/asciidoc-diagram-block-delimiter.adoc[asciidocDiagramBlockDelimiter]* - defines the block delimiter of the  
asciidoc diagram block - default is ``----``; optional 
(only used when enableAsciidocWrapper is true);
** *xref:class-diagram/config/enable-asciidoc-wrapper.adoc[enableAsciidocWrapper]* - a boolean which defines if the generated diagram should be wrapped
by an asciidoc diagram block - default is ``false``; optional;
** *xref:class-diagram/config/field-blacklist-regexp.adoc[fieldBlacklistRegexp]* -
  a regular expression to remove special fields from the diagram; optional
** *xref:class-diagram/config/field-classifier-to-ignore.adoc[fieldClassifierListToIgnore]* -
  a list of classifiers which mark fields as to be ignored during the creation of the diagram
** *xref:class-diagram/config/hide-classes.adoc[hideClasses]* -
  a string list of all classes which should be hidden in the resultign class diagram; optional
** *xref:class-diagram/config/hide-fields.adoc[hideFields]* -
  simple toggle to hide field information in the Plant UML diagram; optional, defaults to ``false`` +
  adds the "hide fields" command to the Plant UML diagram, but the fields are still part of the diagram text
** *xref:class-diagram/config/hide-methods.adoc[hideMethods]* - 
  simple toggle to hide method information in the Plant UML diagram; optional, defaults to ``false`` +
  adds the "hide methods" command to the Plant UML diagram, but the methods are still part of the diagram text
** *xref:class-diagram/config/max-visibility-fields.adoc[maxVisibilityFields]* -
  a toggle to remove fields with a special visibility; defaults to ``PRIVATE``; if you set it to
  *** PUBLIC - only public fields will be displayed
  *** PROTECTED - only public and protected fields will be displayed
  *** PACKAGE_PRIVATE - only public, protected and package_private fields will be displayed
  *** PRIVATE - all fields will be displayed if not removed or ignored by other parameters
** *xref:class-diagram/config/max-visibility-methods.adoc[maxVisibilityMethods]* -
  a toggle to remove methods with a special visibility; defaults to ``PRIVATE``; if you set it to
  *** PUBLIC - only public methods will be displayed
  *** PROTECTED - only public and protected methods will be displayed
  *** PACKAGE_PRIVATE - only public, protected and package_private methods will be displayed
  *** PRIVATE - all methods will be displayed if not removed or ignored by other parameters
** *xref:class-diagram/config/method-blacklist-regexp.adoc[methodBlacklistRegexp]* -
  a regular expression to remove special methods from the diagram; optional
** *xref:class-diagram/config/method-classifier-to-ignore.adoc[methodClassifierListToIgnore]* -
  a list of classifiers which mark methods as to be ignored during the creation of the diagram
** *xref:class-diagram/config/output-directory.adoc[outputDirectory]* -  
  the target folder where the diagram file is written; defaults to ``target/generated-docs``
** *xref:class-diagram/config/remove-fields.adoc[removeFields]* -
  simple toggle to remove all field information in the Plant UML diagram; optional, defaults to ``false`` +
  no field information will be part of the diagram text
** *xref:class-diagram/config/remove-methods.adoc[removeMethods]* - 
  simple toggle to remove all method information in the Plant UML diagram; optional, defaults to ``false`` +
  no method information will be part of the diagram text
  
