= Sequence diagram generator mojo

If you want to use the plantuml-generator-maven-plugin for sequence diagram 
generation, you need to configure this plugin as any normal maven plugin 
as part of your build and add this plugin specific configuration:

* required configuration parameters:
** *xref:sequence-diagram/config/output-directory.adoc[outputDirectory]* -  
  the target folder where the diagram file is written; defaults to ``target/generated-docs``
** *xref:sequence-diagram/config/output-filename.adoc[outputFilename]* - 
  the file name of the diagram generated by this plugin; required
** *xref:sequence-diagram/config/start-class.adoc[startClass]* -
  the name of the class where the sequence diagram should start the call
  flow; required
** *xref:sequence-diagram/config/start-method.adoc[startMethod]* - 
  the *unique* name of the method where the sequence diagram should start the
  call flow; required

* optional configuration options:
** *xref:sequence-diagram/config/asciidoc-diagram-block-delimiter.adoc[asciidocDiagramBlockDelimiter]* - defines the block delimiter of the  
asciidoc diagram block - default is ``----``; optional 
(only used when enableAsciidocWrapper is true);
** *xref:sequence-diagram/config/asciidoc-diagram-image-format.adoc[asciidocDiagramImageFormat]* - the image format (png/svg/latex etc.) - default is ``png``; optional
(only used when enableAsciidocWrapper is true);
** *xref:sequence-diagram/config/asciidoc-diagram-name.adoc[asciidocDiagramName]* - the name of the diagram in the asciidoc diagram block - 
default is outputFilename + "." + asciidocDiagramImageType;optional
(only used when enableAsciidocWrapper is true);
** *xref:sequence-diagram/config/class-blacklist-regexp.adoc[classBlacklistRegexp]* -
  With the help of this configuration parameter it is possible to remove classes from 
  the call sequence flow.
** *xref:sequence-diagram/config/enable-asciidoc-wrapper.adoc[enableAsciidocWrapper]* - a boolean which defines if the generated diagram should be wrapped
by an asciidoc diagram block - default is ``false``; optional;
** *xref:sequence-diagram/config/enable-markdown-wrapper.adoc[enableMarkdownWrapper]* - a boolean which defines if the generated diagram should be wrapped
by an markdown diagram block - default is ``false``; optional;
** *xref:sequence-diagram/config/hide-method-name.adoc[hideMethodName]* -
  With the help of this configuration parameter it is possible to hide/remove the 
  method names from the sequence diagram.
** *xref:sequence-diagram/config/hide-super-class.adoc[hideSuperClass]* -
  With the help of this configuration parameter it is possible to show the method 
  call as part of the child class instead of the super class.
** *xref:sequence-diagram/config/ignore-jpa-entities.adoc[ignoreJPAEntities]* -
  With the help of this configuration toggle it is possible to remove all calls to a 
  JPA entity from the sequence flow.
** *xref:sequence-diagram/config/ignore-standard-classes.adoc[ignoreStandardClasses]* - 
  With the help of this configuration parameter it is possible to remove all Java standard 
  classes (java.* package names) from the call sequence.
** *xref:sequence-diagram/config/method-blacklist-regexp.adoc[methodBlacklistRegexp]* - 
  With the help of this configuration parameter it is possible to ignore/remove specific 
  method calls and their subsequent calls from the sequence flow.
** *xref:sequence-diagram/config/show-return-types.adoc[showReturnTypes]* - 
  With the help of this configuration parameter it is possible to show the type of 
  the returned objects of a method call.
** *xref:sequence-diagram/config/use-short-class-names.adoc[useShortClassNames]* - 
  With the help of this configuration toggle it is possible to show only the class names 
  in the diagram without the package name (full qualified).
