= Sequence diagram generator mojo

If you want to use the plantuml-generator-maven-plugin for sequence diagram generation,
you need to configure this plugin as any normal maven plugin as part of your build and 
add this plugin specific configuration:


* *outputDirectory* -  
  the target folder where the diagram file is written; defaults to ``target/generated-docs``
* *outputFilename* - 
  the file name of the diagram generated by this plugin; required
* *hideFields* -
  simple toggle to hide field information in the Plant UML diagram; optional, defaults to ``false`` +
  adds the "hide fields" command to the Plant UML diagram, but the fields are still part of the diagram text
* *hideMethods* - 
  simple toggle to hide method information in the Plant UML diagram; optional, defaults to ``false`` +
  adds the "hide methods" command to the Plant UML diagram, but the methods are still part of the diagram text
* *removeFields* -
  simple toggle to remove all field information in the Plant UML diagram; optional, defaults to ``false`` +
  no field information will be part of the diagram text
* *removeMethods* - 
  simple toggle to remove all method information in the Plant UML diagram; optional, defaults to ``false`` +
  no method information will be part of the diagram text
* *fieldBlacklistRegexp* -
  a regular expression to remove special fields from the diagram; optional
* *methodBlacklistRegexp* -
  a regular expression to remove special methods from the diagram; optional
* *maxVisibilityFields* -
  a toggle to remove fields with a special visibility; defaults to ``PRIVATE``; if you set it to
  ** PUBLIC - only public fields will be displayed
  ** PROTECTED - only public and protected fields will be displayed
  ** PACKAGE_PRIVATE - only public, protected and package_private fields will be displayed
  ** PRIVATE - all fields will be displayed if not removed or ignored by other parameters
* *maxVisibilityMethods* -
  a toggle to remove methods with a special visibility; defaults to ``PRIVATE``; if you set it to
  ** PUBLIC - only public methods will be displayed
  ** PROTECTED - only public and protected methods will be displayed
  ** PACKAGE_PRIVATE - only public, protected and package_private methods will be displayed
  ** PRIVATE - all methods will be displayed if not removed or ignored by other parameters
* *fieldClassifierListToIgnore* -
  a list of classifiers which mark fields as to be ignored during the creation of the diagram
* *methodClassifierListToIgnore* -
  a list of classifiers which mark methods as to be ignored during the creation of the diagram
* *scanPackages* -
  a string list of all packages which should be used to generate the class diagram; 
  required in conjunction with the blacklist regular expression and optional with the
  whitelist regular expression
* *whitelistRegexp* - a regular expression to filter all classes in the classpath which 
should be part of the diagram (processing can be speed up with the scanPackages 
configuration); optional +
if a whitelist regular expression is configured the blacklist regular expression is ignored!
* *blacklistRegexp* - a regular expression to remove classes from the list of classes in the 
diagram - works only if the configuration parameter scanPackages is not empty and no 
whitelist regular expression is defined; optional
* *hideClasses* -
  a string list of all classes which should be hidden in the resultign class diagram; optional
* *enableAsciidocWrapper* - a boolean which defines if the generated diagram should be wrapped
by an asciidoc diagram block - default is ``false``; optional;
* *asciidocDiagramName* - the name of the diagram in the asciidoc diagram block - 
default is outputFilename + "." + asciidocDiagramImageType;optional
(only used when enableAsciidocWrapper is true);
* *asciidocDiagramImageFormat* - the image format (png/svg/latex etc.) - default is ``png``; optional
(only used when enableAsciidocWrapper is true);
* *asciidocDiagramBlockDelimiter* - defines the block delimiter of the  
asciidoc diagram block - default is ``----``; optional 
(only used when enableAsciidocWrapper is true);
* *addJPAAnnotations* - a boolean to express if JPA-annotations should be shown in
the diagram; optional - Default ``false`` +
Currently implemented JPA Annotations are javax.persistence.Column, javax.persistence.Id, javax.persistence.Transient, 
javax.persistence.OneToOne, javax.persistence.OneToMany, javax.persistence.ManyToMany, javax.persistence.ManyToOne,
javax.persistence.Entity, javax.persistence.Table, javax.persistence.MappedSuperclass, javax.persistence.Index and
javax.persistence.UniqueConstraint +
Index, UniqueConstraint, Tablename and Tableschema are show as tagged values in a separate compartment
  
