= {page-component-title}

== Description
:description: The PlantUML generator utility submodule project of the PlantUML Generator project is documented here.
:keywords: {compontentkeywords} 

The artifact plantuml-generator-util contains two Utility classes: 

* xref:./class-diagram-generator.adoc[PlantUMLClassDiagramGenerator] +
for generation of class diagrams 
* xref:./sequence-diagram-generator.adoc[PlantUMLSequenceDiagramGenerator] +
for generation of sequence diagrams

Both can be used to generate a PlantUML diagram text out of existing java 
classes. 
You can use this string as input for the link:http://plantuml.com/starting[PlantUML tools]
or as part of your "living" documentation 
(for example with link:http://asciidoc.org/[asciidoc])


== Usage

To use this utility library you need to add the plantuml-generator-util.jar 
to your classpath. 

If you use maven as build tool this is easy, just add the following dependency:
[source, xml]
----
<dependency>
	<groupId>de.elnarion.util</groupId>
	<artifactId>plantuml-generator-util</artifactId>
	<version>{generatorversion}</version>
</dependency>		
----
to your pom.xml .

Afterwards just create a PlantUMLClassDiagramConfigBuilder for class diagrams 
or a PlantUML SequenceDiagramConfigBuilder for sequence diagrams.
Add them to the corresponding generator class and start the generation of
the diagram text:

=== Class diagram

include::partial$_class_diagram_example.adoc[]

=== Sequence diagram

include::partial$_sequence_diagram_example.adoc[]
 
