= {page-component-title}

== Description
:description: The PlantUML generator utility submodule project of the PlantUML Generator project is documented here.
:keywords: {compontentkeywords} 

The artifact plantuml-generator-util contains two Utility classes: 

* xref:./class-diagram.adoc[PlantUMLClassDiagramGenerator] +
for generation of class diagrams 
* xref:./sequence-diagram.adoc[PlantUMLSequenceDiagramGenerator] +
for generation of sequence diagrams

Both can be used to generate a PlantUML diagram text out of existing java 
classes. 
You can use this string as input for the link:http://plantuml.com/starting[PlantUML tools]
or as part of your "living" documentation 
(for example with link:http://asciidoc.org/[asciidoc])


== Usage

To use this utility library you need to add the plantuml-generator-util.jar 
to your classpath. 

If you use maven as build tool this is easy, just add the following dependency:
[source, xml]
----
<dependency>
	<groupId>de.elnarion.util</groupId>
	<artifactId>plantuml-generator-util</artifactId>
	<version>{generatorversion}</version>
</dependency>		
----
to your pom.xml .

Afterwards just create a PlantUMLClassDiagramConfigBuilder for class diagrams 
or a PlantUML SequenceDiagramConfigBuilder for sequence diagrams.
Add them to the corresponding generator class and start the generation of
the diagram text:

=== Class diagram

include::partial$_class_diagram_example.adoc[]

=== Sequence diagram

include::partial$_sequence_diagram_example.adoc[]

=== Upgrade from 1.x to 2.x

With the new version 2.x some classes moved to other packages to better
distinguish between classes for class diagrams and those for sequence diagrams.

* the following class moved to de.elnarion.util.plantuml.generator.classdiagram
** PlantUMLClassDiagramGenerator
* the following classes moved to de.elnarion.util.plantuml.generator.classdiagram.config
** PlantUMLClassDiagramConfigBuilder 
** ClassifierType
** VisibilityType

So you need to switch to the new packages.

Furthermore the deprecated constructors of PlantUMLClassDiagramGenerator
have been removed. 
Use the PlantUMLClassDiagramConfigBuilder instead.

=== Upgrade from 2.x to 3.x

With the new version 3.x the configuration parameter
*addJavaxValidationAnnotations* of the PlantUMLClassDiagramGenerator has changed to *addValidationAnnotations*
and now supports javax and jakarta namespace for validations.
So you need to change your configuration if you used this parameter.
 
