= Sequence diagram generator
:keywords: {compontentkeywords}, sequence diagram

The artifact plantuml-generator-util contains a Utility class with the name
PlantUMLSequenceDiagramGenerator which can be used to generate a PlantUML 
sequence diagram text out of existing java classes. 

All you have to do is:

* to provide 
** a start class name where the first method call of the sequence happens
** a start method name which is the starting point of the sequence diagram
(needs to be unique or else one of the possible methods is randomly used)
* add additional configuration to the PlantUMLSequenceDiagramConfig object 
via the PlantUMLSequenceDiagramConfigBuilder to customize the diagram 

After you created the generator object with a PlantUMLSequenceDiagramConfig 
object - build by PlantUMLSequenceDiagramConfigBuilder - simply call the method 
generateDiagramText and you'll get the PlantUML sequence diagram as text.

For more options to customize the diagram text and corresponding examples
have a look at the
xref:./sequence-diagram-generator/config.adoc[configuration] 
documentation.

