= maxVisibilityMethods
include::./_attributes.adoc[]

include::plantuml-generator-util:ROOT:partial$class-diagram/max-visibility-methods.adoc[leveloffset=+1]

== Example
In the following example there are three dependencies in the maven 
dependency hierarchy which build the classpath for all further generation:

[source,xml]
----
include::example$itresources/classdiagram/0010-max-visibility-fields-it/pom.xml[tags=dependencies]
----

From this classpath all classes of the package "de.elnarion.test.domain.t0014",
which are also used by the 
xref:plantuml-generator-util:ROOT:class-diagram/config/max-visibility-methods.adoc[JUnit-tests of the PlantUML generator utility],
should be generated as class diagram with the following plugin configuration

[source,xml]
----
include::example$itresources/classdiagram/0011-max-visibility-methods-it/pom.xml[tags=mvn]
----

but their maximum visibility for fields is limited to PROTECTED.
How this is rendered and how the generated diagram looks like is shown
in the following subchapters.

=== Maximum visibility public
Here the value is set to PUBLIC
which is rendered this way:

[plantuml,0013_max_visibility_methods_public_diagram,png]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_public.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_public.txt[]
----

=== Maximum visibility protected
Here the value is set to PROTECTED
which is rendered this way:

[plantuml,0013_max_visibility_methods_protected_diagram,png]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_protected.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_protected.txt[]
----

=== Maximum visibility package private
Here the value is set to PACKAGE_PRIVATE
which is rendered this way:

[plantuml,0013_max_visibility_methods_package_private_diagram,png]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_package_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_package_private.txt[]
----

=== Maximum visibility private
Here the value is set to PRIVATE
which is rendered this way:

[plantuml,0013_max_visibility_methods_private_diagram,png]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_private.txt[]
----


and produces this PlantUML diagram text:

[source,plantuml,indent=0]
----
include::plantuml-generator-util:ROOT:example$testresources/class/0014_max_visibility_methods_private.txt[]
----

